steps:
- name: node
  entrypoint: npm
  args: ['install']
- name: node
  entrypoint: npm
  args: ['run', 'build']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ["-m", "rsync", "-r", "./build", "gs://www.scentographers.com"]
options:
  logging: CLOUD_LOGGING_ONLY
